local compass_env_argument_tree = {'development', 'production'}
local compass_output_style_argument_tree = {'nested', 'expanded', 'compact', 'compressed'}

local compass_argument_tree = {
	'clean',
	'compile',
	create = {
			'--using',
			'-x', '--syntax',
			'--prepare',
			'-r', '--require',
			'-l', '--load',
			'-L', '--load-all',
			'-I',
			'-q', '--quiet',
			'--trace',
			'--force',
			'--dry-run',
			'--boring',
			'-c', '--config',
			'--app',
			'--sass-dir',
			'--css-dir',
			'--images-dir',
			'--javascripts-dir',
			'--fonts-dir',
			'-e', '--environment',
			'-s', '--output-style',
			'--relative-assets',
			'--no-line-comments',
			'--bare',
			'-?', '-h', '--help'
		},
	'init',
	'watch',
	'config',
	'extension',
	'frameworks',
	'grid-img',
	'imports',
	'install',
	'interactive',
	'sprite',
	'stats',
	'unpack',
	'validate',
	'version',
	help = {
		'clean',
		'compile',
		'create',
		'init',
		'watch',
		'config',
		'extension',
		'frameworks',
		'grid-img',
		'imports',
		'install',
		'interactive',
		'sprite',
		'stats',
		'unpack',
		'validate',
		'version'
	}	
}
clink.arg.register_tree("compass", compass_argument_tree)
